import { Geist, Geist_Mono, Pixelify_Sans, Press_Start_2P } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import FGFooter from "./components/FGFooter";
import { AppContextProvider } from "@/context/ShopContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pressStart = Press_Start_2P({
  variable:"--font-ps2p",
  subsets:["latin"],
  weight:["400"],
});

const pixelify = Pixelify_Sans({
  subsets:["latin"],
  variable:"--font-pixelify",
    weight:["400"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pixelify.variable} ${pressStart.variable} antialiased`}
      >
        <AppContextProvider>
          <NavBar/>
            {children}
          <FGFooter/>
        </AppContextProvider>
      </body>
    </html>
  );
}
